version: "3"

services:
  greengrass:
    container_name: greengrass
    image: amazon/aws-iot-greengrass:latest
    volumes:
      - ./greengrass/certs:/greengrass/certs
      - ./greengrass/config:/greengrass/config
      - ./greengrass/log:/greengrass/ggc/var/log
    ports:
      - 8883:8883
    entrypoint: /greengrass-entrypoint.sh
    privileged: true
    env_file: 
      - .env